version: '3.8'

services:
  backend:
    build:
      context: ./server
      target: production
    container_name: login_site_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - API_ENCRYPTION_KEY=sharmamilu_login_site_secret_encryption_key_2026

  frontend:
    build:
      context: .
      target: production
    container_name: login_site_frontend
    restart: always
    ports:
      - "8080:80" # Host port 8080, Container port 80
    depends_on:
      - backend
