server {
    server_name milancodes.shop www.milancodes.shop;

    # Reverse proxy Web traffic to the Frontend Docker container
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Reverse proxy API traffic to the Backend Docker container
    location /api/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # SSL Configuration (Managed by Certbot on host)
    listen [::]:443 ssl ipv6only=on; 
    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/milancodes.shop/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/milancodes.shop/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}

server {
    if ($host = www.milancodes.shop) {
        return 301 https://$host$request_uri;
    } 

    if ($host = milancodes.shop) {
        return 301 https://$host$request_uri;
    } 

    listen 80 default_server;
    listen [::]:80 default_server;
    server_name milancodes.shop www.milancodes.shop;
    return 404; 
}
